# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab9e1bbc6c47ed36106539618ee9f76caa185a618d93b2f650ca4e22da9055676e0dcd0d7d08b872100f723482ffa4a583a3566a885d048ef338589458a01162

test:
  secret_key_base: e417697dacc0cc42d18834d03051543141d524edb7df6f87ba7325412d874aa2a61194e9673c8081c373d2980be62235619f7f4a8331171ec6960444b00fbba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
